remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Titel und Logo für dieses Theme
title: My Map
logo: https://www.google.com/search?q=snake%20logo%20white%20mamba&tbm=isch&tbs=il:cl&rlz=1C1GCEA_enCH822CH822&hl=de&sa=X&ved=0CAAQ1vwEahcKEwjwtJmo7rD-AhUAAAAAHQAAAAAQAg&biw=1903&bih=890#imgrc=5rPISsBLjh1hrM/logo.jpeg
